In [1]:
import sys
from pathlib import Path

ROOT = Path.cwd().parents[1]

sys.path.append(str(ROOT))

import pandas as pd

from src.feature_selection.rfe_random_forest import run_rfe_random_forest

In [2]:
data_path = ROOT / "data/processed/ml_dataset.csv"

df = pd.read_csv(data_path)

df["trade_date"] = pd.to_datetime(df["trade_date"])

df.head()

,stock_code,trade_date,return_1d,return_5d,return_10d,return_20d,intraday_return,high_low_range,gap,sma_5,...,macd,macd_signal,macd_hist,volatility_5,volatility_20,atr_14,volume_change_1d,volume_sma_20,volume_ratio_20,target_return_5d
0,660,2024-06-11,0.021635,0.094233,0.054591,0.181212,0.011905,0.043689,0.009615,203000.0,...,6187.902397,5195.016563,992.885834,0.031048,0.023996,6757.468051,0.253659,3435519.80,0.893653,0.103529
1,660,2024-06-12,0.011765,0.112261,0.061728,0.169750,0.014151,0.023697,-0.002353,207340.0,...,6911.664995,5538.346249,1373.318746,0.028770,0.023814,6631.934619,-0.299278,3381585.20,0.636190,0.086047
2,660,2024-06-13,0.032558,0.146102,0.096296,0.198057,-0.017699,0.034247,0.051163,213000.0,...,7958.354609,6022.347921,1936.006687,0.026692,0.024432,6979.653575,1.685444,3532295.70,1.635559,0.069820
3,660,2024-06-14,-0.004505,0.065060,0.129280,0.145078,-0.017778,0.041667,0.013514,215700.0,...,8607.944994,6539.467336,2068.477659,0.014806,0.023386,7123.964034,-0.426854,3443697.95,0.961531,0.058824
4,660,2024-06-17,0.009050,0.072115,0.178647,0.174302,0.018265,0.047945,-0.009050,218700.0,...,9178.331251,7067.240119,2111.091132,0.013915,0.022745,7365.109460,-0.336094,3411545.25,0.644382,0.000000

In [3]:
target = "return_5d"

train_df = df[
    (df["trade_date"] >= "2024-03-13") &
    (df["trade_date"] <= "2025-12-31")
].copy()

valid_df = df[
    (df["trade_date"] >= "2026-01-01") &
    (df["trade_date"] <= "2026-06-30")
].copy()

features = [
    col
    for col in df.columns
    if col not in ["stock_code", "trade_date", target]
]

print("Train:", train_df.shape)
print("Validation:", valid_df.shape)
print("Feature count:", len(features))
print(features)

Train: (1895, 28)
Validation: (600, 28)
Feature count: 25
['return_1d', 'return_10d', 'return_20d', 'intraday_return', 'high_low_range', 'gap', 'sma_5', 'sma_20', 'sma_60', 'price_to_sma_5', 'price_to_sma_20', 'price_to_sma_60', 'rsi_14', 'roc_10', 'roc_20', 'macd', 'macd_signal', 'macd_hist', 'volatility_5', 'volatility_20', 'atr_14', 'volume_change_1d', 'volume_sma_20', 'volume_ratio_20', 'target_return_5d']

In [4]:
rfe_rf_results = run_rfe_random_forest(
    train_df=train_df,
    valid_df=valid_df,
    features=features,
    target=target,
)

print(f"총 실험 수: {len(rfe_rf_results)}")

rfe_rf_results.head(10)

[1/405] k=5, step=1, n_estimators=100, max_depth=None, max_features=sqrt
[2/405] k=5, step=1, n_estimators=100, max_depth=None, max_features=log2
[3/405] k=5, step=1, n_estimators=100, max_depth=None, max_features=0.5
[4/405] k=5, step=1, n_estimators=100, max_depth=5, max_features=sqrt
[5/405] k=5, step=1, n_estimators=100, max_depth=5, max_features=log2
[6/405] k=5, step=1, n_estimators=100, max_depth=5, max_features=0.5
[7/405] k=5, step=1, n_estimators=100, max_depth=10, max_features=sqrt
[8/405] k=5, step=1, n_estimators=100, max_depth=10, max_features=log2
[9/405] k=5, step=1, n_estimators=100, max_depth=10, max_features=0.5
[10/405] k=5, step=1, n_estimators=300, max_depth=None, max_features=sqrt
[11/405] k=5, step=1, n_estimators=300, max_depth=None, max_features=log2
[12/405] k=5, step=1, n_estimators=300, max_depth=None, max_features=0.5
[13/405] k=5, step=1, n_estimators=300, max_depth=5, max_features=sqrt
[14/405] k=5, step=1, n_estimators=300, max_depth=5, max_features=log2
[15/405] k=5, step=1, n_estimators=300, max_depth=5, max_features=0.5
[16/405] k=5, step=1, n_estimators=300, max_depth=10, max_features=sqrt
[17/405] k=5, step=1, n_estimators=300, max_depth=10, max_features=log2
[18/405] k=5, step=1, n_estimators=300, max_depth=10, max_features=0.5
[19/405] k=5, step=1, n_estimators=500, max_depth=None, max_features=sqrt
[20/405] k=5, step=1, n_estimators=500, max_depth=None, max_features=log2
[21/405] k=5, step=1, n_estimators=500, max_depth=None, max_features=0.5
[22/405] k=5, step=1, n_estimators=500, max_depth=5, max_features=sqrt
[23/405] k=5, step=1, n_estimators=500, max_depth=5, max_features=log2
[24/405] k=5, step=1, n_estimators=500, max_depth=5, max_features=0.5
[25/405] k=5, step=1, n_estimators=500, max_depth=10, max_features=sqrt
[26/405] k=5, step=1, n_estimators=500, max_depth=10, max_features=log2
[27/405] k=5, step=1, n_estimators=500, max_depth=10, max_features=0.5
[28/405] k=5, step=2, n_estimators=100, max_depth=None, max_features=sqrt
[29/405] k=5, step=2, n_estimators=100, max_depth=None, max_features=log2
[30/405] k=5, step=2, n_estimators=100, max_depth=None, max_features=0.5
[31/405] k=5, step=2, n_estimators=100, max_depth=5, max_features=sqrt
[32/405] k=5, step=2, n_estimators=100, max_depth=5, max_features=log2
[33/405] k=5, step=2, n_estimators=100, max_depth=5, max_features=0.5
[34/405] k=5, step=2, n_estimators=100, max_depth=10, max_features=sqrt
[35/405] k=5, step=2, n_estimators=100, max_depth=10, max_features=log2
[36/405] k=5, step=2, n_estimators=100, max_depth=10, max_features=0.5
[37/405] k=5, step=2, n_estimators=300, max_depth=None, max_features=sqrt
[38/405] k=5, step=2, n_estimators=300, max_depth=None, max_features=log2
[39/405] k=5, step=2, n_estimators=300, max_depth=None, max_features=0.5
[40/405] k=5, step=2, n_estimators=300, max_depth=5, max_features=sqrt
[41/405] k=5, step=2, n_estimators=300, max_depth=5, max_features=log2
[42/405] k=5, step=2, n_estimators=300, max_depth=5, max_features=0.5
[43/405] k=5, step=2, n_estimators=300, max_depth=10, max_features=sqrt
[44/405] k=5, step=2, n_estimators=300, max_depth=10, max_features=log2
[45/405] k=5, step=2, n_estimators=300, max_depth=10, max_features=0.5
[46/405] k=5, step=2, n_estimators=500, max_depth=None, max_features=sqrt
[47/405] k=5, step=2, n_estimators=500, max_depth=None, max_features=log2
[48/405] k=5, step=2, n_estimators=500, max_depth=None, max_features=0.5
[49/405] k=5, step=2, n_estimators=500, max_depth=5, max_features=sqrt
[50/405] k=5, step=2, n_estimators=500, max_depth=5, max_features=log2
[51/405] k=5, step=2, n_estimators=500, max_depth=5, max_features=0.5
[52/405] k=5, step=2, n_estimators=500, max_depth=10, max_features=sqrt
[53/405] k=5, step=2, n_estimators=500, max_depth=10, max_features=log2
[54/405] k=5, step=2, n_estimators=500, max_depth=10, max_features=0.5
[55/405] k=5, step=0.1, n_estimators=100, max_depth=None, max_features=sqrt
[56/405] k=5, step=0.1, n_estimators=100, max_depth=None, max_features=log2
[57/405] k=5, step=0.1, n_estimators=100, max_depth=None, max_features=0.5
[58/405] k=5, step=0.1, n_estimators=100, max_depth=5, max_features=sqrt
[59/405] k=5, step=0.1, n_estimators=100, max_depth=5, max_features=log2
[60/405] k=5, step=0.1, n_estimators=100, max_depth=5, max_features=0.5
[61/405] k=5, step=0.1, n_estimators=100, max_depth=10, max_features=sqrt
[62/405] k=5, step=0.1, n_estimators=100, max_depth=10, max_features=log2
[63/405] k=5, step=0.1, n_estimators=100, max_depth=10, max_features=0.5
[64/405] k=5, step=0.1, n_estimators=300, max_depth=None, max_features=sqrt
[65/405] k=5, step=0.1, n_estimators=300, max_depth=None, max_features=log2
[66/405] k=5, step=0.1, n_estimators=300, max_depth=None, max_features=0.5
[67/405] k=5, step=0.1, n_estimators=300, max_depth=5, max_features=sqrt
[68/405] k=5, step=0.1, n_estimators=300, max_depth=5, max_features=log2
[69/405] k=5, step=0.1, n_estimators=300, max_depth=5, max_features=0.5
[70/405] k=5, step=0.1, n_estimators=300, max_depth=10, max_features=sqrt
[71/405] k=5, step=0.1, n_estimators=300, max_depth=10, max_features=log2
[72/405] k=5, step=0.1, n_estimators=300, max_depth=10, max_features=0.5
[73/405] k=5, step=0.1, n_estimators=500, max_depth=None, max_features=sqrt
[74/405] k=5, step=0.1, n_estimators=500, max_depth=None, max_features=log2
[75/405] k=5, step=0.1, n_estimators=500, max_depth=None, max_features=0.5
[76/405] k=5, step=0.1, n_estimators=500, max_depth=5, max_features=sqrt
[77/405] k=5, step=0.1, n_estimators=500, max_depth=5, max_features=log2
[78/405] k=5, step=0.1, n_estimators=500, max_depth=5, max_features=0.5
[79/405] k=5, step=0.1, n_estimators=500, max_depth=10, max_features=sqrt
[80/405] k=5, step=0.1, n_estimators=500, max_depth=10, max_features=log2
[81/405] k=5, step=0.1, n_estimators=500, max_depth=10, max_features=0.5
[82/405] k=10, step=1, n_estimators=100, max_depth=None, max_features=sqrt
[83/405] k=10, step=1, n_estimators=100, max_depth=None, max_features=log2
[84/405] k=10, step=1, n_estimators=100, max_depth=None, max_features=0.5
[85/405] k=10, step=1, n_estimators=100, max_depth=5, max_features=sqrt
[86/405] k=10, step=1, n_estimators=100, max_depth=5, max_features=log2
[87/405] k=10, step=1, n_estimators=100, max_depth=5, max_features=0.5
[88/405] k=10, step=1, n_estimators=100, max_depth=10, max_features=sqrt
[89/405] k=10, step=1, n_estimators=100, max_depth=10, max_features=log2
[90/405] k=10, step=1, n_estimators=100, max_depth=10, max_features=0.5
[91/405] k=10, step=1, n_estimators=300, max_depth=None, max_features=sqrt
[92/405] k=10, step=1, n_estimators=300, max_depth=None, max_features=log2
[93/405] k=10, step=1, n_estimators=300, max_depth=None, max_features=0.5
[94/405] k=10, step=1, n_estimators=300, max_depth=5, max_features=sqrt
[95/405] k=10, step=1, n_estimators=300, max_depth=5, max_features=log2
[96/405] k=10, step=1, n_estimators=300, max_depth=5, max_features=0.5
[97/405] k=10, step=1, n_estimators=300, max_depth=10, max_features=sqrt
[98/405] k=10, step=1, n_estimators=300, max_depth=10, max_features=log2
[99/405] k=10, step=1, n_estimators=300, max_depth=10, max_features=0.5
[100/405] k=10, step=1, n_estimators=500, max_depth=None, max_features=sqrt
[101/405] k=10, step=1, n_estimators=500, max_depth=None, max_features=log2
[102/405] k=10, step=1, n_estimators=500, max_depth=None, max_features=0.5
[103/405] k=10, step=1, n_estimators=500, max_depth=5, max_features=sqrt
[104/405] k=10, step=1, n_estimators=500, max_depth=5, max_features=log2
[105/405] k=10, step=1, n_estimators=500, max_depth=5, max_features=0.5
[106/405] k=10, step=1, n_estimators=500, max_depth=10, max_features=sqrt
[107/405] k=10, step=1, n_estimators=500, max_depth=10, max_features=log2
[108/405] k=10, step=1, n_estimators=500, max_depth=10, max_features=0.5
[109/405] k=10, step=2, n_estimators=100, max_depth=None, max_features=sqrt
[110/405] k=10, step=2, n_estimators=100, max_depth=None, max_features=log2
[111/405] k=10, step=2, n_estimators=100, max_depth=None, max_features=0.5
[112/405] k=10, step=2, n_estimators=100, max_depth=5, max_features=sqrt
[113/405] k=10, step=2, n_estimators=100, max_depth=5, max_features=log2
[114/405] k=10, step=2, n_estimators=100, max_depth=5, max_features=0.5
[115/405] k=10, step=2, n_estimators=100, max_depth=10, max_features=sqrt
[116/405] k=10, step=2, n_estimators=100, max_depth=10, max_features=log2
[117/405] k=10, step=2, n_estimators=100, max_depth=10, max_features=0.5
[118/405] k=10, step=2, n_estimators=300, max_depth=None, max_features=sqrt
[119/405] k=10, step=2, n_estimators=300, max_depth=None, max_features=log2
[120/405] k=10, step=2, n_estimators=300, max_depth=None, max_features=0.5
[121/405] k=10, step=2, n_estimators=300, max_depth=5, max_features=sqrt
[122/405] k=10, step=2, n_estimators=300, max_depth=5, max_features=log2
[123/405] k=10, step=2, n_estimators=300, max_depth=5, max_features=0.5
[124/405] k=10, step=2, n_estimators=300, max_depth=10, max_features=sqrt
[125/405] k=10, step=2, n_estimators=300, max_depth=10, max_features=log2
[126/405] k=10, step=2, n_estimators=300, max_depth=10, max_features=0.5
[127/405] k=10, step=2, n_estimators=500, max_depth=None, max_features=sqrt
[128/405] k=10, step=2, n_estimators=500, max_depth=None, max_features=log2
[129/405] k=10, step=2, n_estimators=500, max_depth=None, max_features=0.5
[130/405] k=10, step=2, n_estimators=500, max_depth=5, max_features=sqrt
[131/405] k=10, step=2, n_estimators=500, max_depth=5, max_features=log2
[132/405] k=10, step=2, n_estimators=500, max_depth=5, max_features=0.5
[133/405] k=10, step=2, n_estimators=500, max_depth=10, max_features=sqrt
[134/405] k=10, step=2, n_estimators=500, max_depth=10, max_features=log2
[135/405] k=10, step=2, n_estimators=500, max_depth=10, max_features=0.5
[136/405] k=10, step=0.1, n_estimators=100, max_depth=None, max_features=sqrt
[137/405] k=10, step=0.1, n_estimators=100, max_depth=None, max_features=log2
[138/405] k=10, step=0.1, n_estimators=100, max_depth=None, max_features=0.5
[139/405] k=10, step=0.1, n_estimators=100, max_depth=5, max_features=sqrt
[140/405] k=10, step=0.1, n_estimators=100, max_depth=5, max_features=log2
[141/405] k=10, step=0.1, n_estimators=100, max_depth=5, max_features=0.5
[142/405] k=10, step=0.1, n_estimators=100, max_depth=10, max_features=sqrt
[143/405] k=10, step=0.1, n_estimators=100, max_depth=10, max_features=log2
[144/405] k=10, step=0.1, n_estimators=100, max_depth=10, max_features=0.5
[145/405] k=10, step=0.1, n_estimators=300, max_depth=None, max_features=sqrt
[146/405] k=10, step=0.1, n_estimators=300, max_depth=None, max_features=log2
[147/405] k=10, step=0.1, n_estimators=300, max_depth=None, max_features=0.5
[148/405] k=10, step=0.1, n_estimators=300, max_depth=5, max_features=sqrt
[149/405] k=10, step=0.1, n_estimators=300, max_depth=5, max_features=log2
[150/405] k=10, step=0.1, n_estimators=300, max_depth=5, max_features=0.5
[151/405] k=10, step=0.1, n_estimators=300, max_depth=10, max_features=sqrt
[152/405] k=10, step=0.1, n_estimators=300, max_depth=10, max_features=log2
[153/405] k=10, step=0.1, n_estimators=300, max_depth=10, max_features=0.5
[154/405] k=10, step=0.1, n_estimators=500, max_depth=None, max_features=sqrt
[155/405] k=10, step=0.1, n_estimators=500, max_depth=None, max_features=log2
[156/405] k=10, step=0.1, n_estimators=500, max_depth=None, max_features=0.5
[157/405] k=10, step=0.1, n_estimators=500, max_depth=5, max_features=sqrt
[158/405] k=10, step=0.1, n_estimators=500, max_depth=5, max_features=log2
[159/405] k=10, step=0.1, n_estimators=500, max_depth=5, max_features=0.5
[160/405] k=10, step=0.1, n_estimators=500, max_depth=10, max_features=sqrt
[161/405] k=10, step=0.1, n_estimators=500, max_depth=10, max_features=log2
[162/405] k=10, step=0.1, n_estimators=500, max_depth=10, max_features=0.5
[163/405] k=15, step=1, n_estimators=100, max_depth=None, max_features=sqrt
[164/405] k=15, step=1, n_estimators=100, max_depth=None, max_features=log2
[165/405] k=15, step=1, n_estimators=100, max_depth=None, max_features=0.5
[166/405] k=15, step=1, n_estimators=100, max_depth=5, max_features=sqrt
[167/405] k=15, step=1, n_estimators=100, max_depth=5, max_features=log2
[168/405] k=15, step=1, n_estimators=100, max_depth=5, max_features=0.5
[169/405] k=15, step=1, n_estimators=100, max_depth=10, max_features=sqrt
[170/405] k=15, step=1, n_estimators=100, max_depth=10, max_features=log2
[171/405] k=15, step=1, n_estimators=100, max_depth=10, max_features=0.5
[172/405] k=15, step=1, n_estimators=300, max_depth=None, max_features=sqrt
[173/405] k=15, step=1, n_estimators=300, max_depth=None, max_features=log2
[174/405] k=15, step=1, n_estimators=300, max_depth=None, max_features=0.5
[175/405] k=15, step=1, n_estimators=300, max_depth=5, max_features=sqrt
[176/405] k=15, step=1, n_estimators=300, max_depth=5, max_features=log2
[177/405] k=15, step=1, n_estimators=300, max_depth=5, max_features=0.5
[178/405] k=15, step=1, n_estimators=300, max_depth=10, max_features=sqrt
[179/405] k=15, step=1, n_estimators=300, max_depth=10, max_features=log2
[180/405] k=15, step=1, n_estimators=300, max_depth=10, max_features=0.5
[181/405] k=15, step=1, n_estimators=500, max_depth=None, max_features=sqrt
[182/405] k=15, step=1, n_estimators=500, max_depth=None, max_features=log2
[183/405] k=15, step=1, n_estimators=500, max_depth=None, max_features=0.5
[184/405] k=15, step=1, n_estimators=500, max_depth=5, max_features=sqrt
[185/405] k=15, step=1, n_estimators=500, max_depth=5, max_features=log2
[186/405] k=15, step=1, n_estimators=500, max_depth=5, max_features=0.5
[187/405] k=15, step=1, n_estimators=500, max_depth=10, max_features=sqrt
[188/405] k=15, step=1, n_estimators=500, max_depth=10, max_features=log2
[189/405] k=15, step=1, n_estimators=500, max_depth=10, max_features=0.5
[190/405] k=15, step=2, n_estimators=100, max_depth=None, max_features=sqrt
[191/405] k=15, step=2, n_estimators=100, max_depth=None, max_features=log2
[192/405] k=15, step=2, n_estimators=100, max_depth=None, max_features=0.5
[193/405] k=15, step=2, n_estimators=100, max_depth=5, max_features=sqrt
[194/405] k=15, step=2, n_estimators=100, max_depth=5, max_features=log2
[195/405] k=15, step=2, n_estimators=100, max_depth=5, max_features=0.5
[196/405] k=15, step=2, n_estimators=100, max_depth=10, max_features=sqrt
[197/405] k=15, step=2, n_estimators=100, max_depth=10, max_features=log2
[198/405] k=15, step=2, n_estimators=100, max_depth=10, max_features=0.5
[199/405] k=15, step=2, n_estimators=300, max_depth=None, max_features=sqrt
[200/405] k=15, step=2, n_estimators=300, max_depth=None, max_features=log2
[201/405] k=15, step=2, n_estimators=300, max_depth=None, max_features=0.5
[202/405] k=15, step=2, n_estimators=300, max_depth=5, max_features=sqrt
[203/405] k=15, step=2, n_estimators=300, max_depth=5, max_features=log2
[204/405] k=15, step=2, n_estimators=300, max_depth=5, max_features=0.5
[205/405] k=15, step=2, n_estimators=300, max_depth=10, max_features=sqrt
[206/405] k=15, step=2, n_estimators=300, max_depth=10, max_features=log2
[207/405] k=15, step=2, n_estimators=300, max_depth=10, max_features=0.5
[208/405] k=15, step=2, n_estimators=500, max_depth=None, max_features=sqrt
[209/405] k=15, step=2, n_estimators=500, max_depth=None, max_features=log2
[210/405] k=15, step=2, n_estimators=500, max_depth=None, max_features=0.5
[211/405] k=15, step=2, n_estimators=500, max_depth=5, max_features=sqrt
[212/405] k=15, step=2, n_estimators=500, max_depth=5, max_features=log2
[213/405] k=15, step=2, n_estimators=500, max_depth=5, max_features=0.5
[214/405] k=15, step=2, n_estimators=500, max_depth=10, max_features=sqrt
[215/405] k=15, step=2, n_estimators=500, max_depth=10, max_features=log2
[216/405] k=15, step=2, n_estimators=500, max_depth=10, max_features=0.5
[217/405] k=15, step=0.1, n_estimators=100, max_depth=None, max_features=sqrt
[218/405] k=15, step=0.1, n_estimators=100, max_depth=None, max_features=log2
[219/405] k=15, step=0.1, n_estimators=100, max_depth=None, max_features=0.5
[220/405] k=15, step=0.1, n_estimators=100, max_depth=5, max_features=sqrt
[221/405] k=15, step=0.1, n_estimators=100, max_depth=5, max_features=log2
[222/405] k=15, step=0.1, n_estimators=100, max_depth=5, max_features=0.5
[223/405] k=15, step=0.1, n_estimators=100, max_depth=10, max_features=sqrt
[224/405] k=15, step=0.1, n_estimators=100, max_depth=10, max_features=log2
[225/405] k=15, step=0.1, n_estimators=100, max_depth=10, max_features=0.5
[226/405] k=15, step=0.1, n_estimators=300, max_depth=None, max_features=sqrt
[227/405] k=15, step=0.1, n_estimators=300, max_depth=None, max_features=log2
[228/405] k=15, step=0.1, n_estimators=300, max_depth=None, max_features=0.5
[229/405] k=15, step=0.1, n_estimators=300, max_depth=5, max_features=sqrt
[230/405] k=15, step=0.1, n_estimators=300, max_depth=5, max_features=log2
[231/405] k=15, step=0.1, n_estimators=300, max_depth=5, max_features=0.5
[232/405] k=15, step=0.1, n_estimators=300, max_depth=10, max_features=sqrt
[233/405] k=15, step=0.1, n_estimators=300, max_depth=10, max_features=log2
[234/405] k=15, step=0.1, n_estimators=300, max_depth=10, max_features=0.5
[235/405] k=15, step=0.1, n_estimators=500, max_depth=None, max_features=sqrt
[236/405] k=15, step=0.1, n_estimators=500, max_depth=None, max_features=log2
[237/405] k=15, step=0.1, n_estimators=500, max_depth=None, max_features=0.5
[238/405] k=15, step=0.1, n_estimators=500, max_depth=5, max_features=sqrt
[239/405] k=15, step=0.1, n_estimators=500, max_depth=5, max_features=log2
[240/405] k=15, step=0.1, n_estimators=500, max_depth=5, max_features=0.5
[241/405] k=15, step=0.1, n_estimators=500, max_depth=10, max_features=sqrt
[242/405] k=15, step=0.1, n_estimators=500, max_depth=10, max_features=log2
[243/405] k=15, step=0.1, n_estimators=500, max_depth=10, max_features=0.5
[244/405] k=20, step=1, n_estimators=100, max_depth=None, max_features=sqrt
[245/405] k=20, step=1, n_estimators=100, max_depth=None, max_features=log2
[246/405] k=20, step=1, n_estimators=100, max_depth=None, max_features=0.5
[247/405] k=20, step=1, n_estimators=100, max_depth=5, max_features=sqrt
[248/405] k=20, step=1, n_estimators=100, max_depth=5, max_features=log2
[249/405] k=20, step=1, n_estimators=100, max_depth=5, max_features=0.5
[250/405] k=20, step=1, n_estimators=100, max_depth=10, max_features=sqrt
[251/405] k=20, step=1, n_estimators=100, max_depth=10, max_features=log2
[252/405] k=20, step=1, n_estimators=100, max_depth=10, max_features=0.5
[253/405] k=20, step=1, n_estimators=300, max_depth=None, max_features=sqrt
[254/405] k=20, step=1, n_estimators=300, max_depth=None, max_features=log2
[255/405] k=20, step=1, n_estimators=300, max_depth=None, max_features=0.5
[256/405] k=20, step=1, n_estimators=300, max_depth=5, max_features=sqrt
[257/405] k=20, step=1, n_estimators=300, max_depth=5, max_features=log2
[258/405] k=20, step=1, n_estimators=300, max_depth=5, max_features=0.5
[259/405] k=20, step=1, n_estimators=300, max_depth=10, max_features=sqrt
[260/405] k=20, step=1, n_estimators=300, max_depth=10, max_features=log2
[261/405] k=20, step=1, n_estimators=300, max_depth=10, max_features=0.5
[262/405] k=20, step=1, n_estimators=500, max_depth=None, max_features=sqrt
[263/405] k=20, step=1, n_estimators=500, max_depth=None, max_features=log2
[264/405] k=20, step=1, n_estimators=500, max_depth=None, max_features=0.5
[265/405] k=20, step=1, n_estimators=500, max_depth=5, max_features=sqrt
[266/405] k=20, step=1, n_estimators=500, max_depth=5, max_features=log2
[267/405] k=20, step=1, n_estimators=500, max_depth=5, max_features=0.5
[268/405] k=20, step=1, n_estimators=500, max_depth=10, max_features=sqrt
[269/405] k=20, step=1, n_estimators=500, max_depth=10, max_features=log2
[270/405] k=20, step=1, n_estimators=500, max_depth=10, max_features=0.5

,method,n_features,step,n_estimators,max_depth,max_features,features,rmse
0,RFE + Random Forest,15,1.0,300,10.0,0.5,"[return_1d, return_10d, return_20d, intraday_r...",0.050424
1,RFE + Random Forest,15,1.0,500,10.0,0.5,"[return_1d, return_10d, return_20d, intraday_r...",0.050466
2,RFE + Random Forest,15,1.0,100,10.0,0.5,"[return_1d, return_10d, return_20d, intraday_r...",0.050483
3,RFE + Random Forest,15,2.0,500,10.0,0.5,"[return_1d, return_10d, return_20d, intraday_r...",0.050606
4,RFE + Random Forest,15,0.1,500,10.0,0.5,"[return_1d, return_10d, return_20d, intraday_r...",0.050606
5,RFE + Random Forest,20,0.1,500,10.0,0.5,"[return_1d, return_10d, return_20d, intraday_r...",0.050616
6,RFE + Random Forest,20,2.0,500,10.0,0.5,"[return_1d, return_10d, return_20d, intraday_r...",0.050616
7,RFE + Random Forest,15,1.0,500,NaN,0.5,"[return_1d, return_10d, return_20d, intraday_r...",0.050633
8,RFE + Random Forest,20,2.0,100,NaN,0.5,"[return_1d, return_10d, return_20d, intraday_r...",0.050666
9,RFE + Random Forest,20,0.1,100,NaN,0.5,"[return_1d, return_10d, return_20d, intraday_r...",0.050666

In [5]:
output_path = ROOT / "data/processed/filter_results/rfe_random_forest_results.csv"

rfe_rf_results.to_csv(
    output_path,
    index=False,
)

print(f"저장 완료: {output_path}")

저장 완료: /Users/yangjaehoon/Desktop/StockLens/data/processed/filter_results/rfe_random_forest_results.csv